export const UserTypes = {
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',

  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

  UN_FRIEND_REQUEST: 'UN_FRIEND_REQUEST',
  UN_FRIEND_SUCCESS: 'UN_FRIEND_SUCCESS',
  UN_FRIEND_FAILURE: 'UN_FRIEND_FAILURE',

  SEARCH_USER_REQUEST: 'SEARCH_USER_REQUEST',
  SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
  SEARCH_USER_FAILURE: 'SEARCH_USER_FAILURE',

  GET_EMAIL_REQUEST: 'GET_EMAIL_REQUEST',
  GET_EMAIL_SUCCESS: 'GET_EMAIL_SUCCESS',
  GET_EMAIL_FAILURE: 'GET_EMAIL_FAILURE',

  CHECK_OTP_REQUEST: 'CHECK_OTP_REQUEST',
  CHECK_OTP_SUCCESS: 'CHECK_OTP_SUCCESS',
  CHECK_OTP_FAILURE: 'CHECK_OTP_FAILURE',

  UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

  GET_NEW_TOKEN_REQUEST: 'GET_NEW_TOKEN_REQUEST',
  GET_NEW_TOKEN_SUCCESS: 'GET_NEW_TOKEN_SUCCESS',
  GET_NEW_TOKEN_FAILURE: 'GET_NEW_TOKEN_FAILURE',

  UPDATE_AVATAR_REQUEST: 'UPDATE_AVATAR_REQUEST',
  UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
  UPDATE_AVATAR_FAILURE: 'UPDATE_AVATAR_FAILURE',

  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',

  GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS: 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAILURE: 'GET_USER_BY_ID_FAILURE',

  GET_CONVERSATION_BY_ID_REQUEST: 'GET_CONVERSATION_BY_ID_REQUEST',
  GET_CONVERSATION_BY_ID_SUCCESS: 'GET_CONVERSATION_BY_ID_SUCCESS',
  GET_CONVERSATION_BY_ID_FAILURE: 'GET_CONVERSATION_BY_ID_FAILURE',

  GET_FRIEND_BY_ID_REQUEST: 'GET_FRIEND_BY_ID_REQUEST',
  GET_FRIEND_BY_ID_SUCCESS: 'GET_FRIEND_BY_ID_SUCCESS',
  GET_FRIEND_BY_ID_FAILURE: 'GET_FRIEND_BY_ID_FAILURE',

  GET_ALL_FRIEND_REQUEST: 'GET_ALL_FRIEND_REQUEST',
  GET_ALL_FRIEND_SUCCESS: 'GET_ALL_FRIEND_SUCCESS',
  GET_ALL_FRIEND_FAILURE: 'GET_ALL_FRIEND_FAILURE',

  GET_ALL_PEOPLE_REQUEST_REQUEST: 'GET_ALL_PEOPLE_REQUEST_REQUEST',
  GET_ALL_PEOPLE_REQUEST_SUCCESS: 'GET_ALL_PEOPLE_REQUEST_SUCCESS',
  GET_ALL_PEOPLE_REQUEST_FAILURE: 'GET_ALL_PEOPLE_REQUEST_FAILURE',

  SAVE_EMAIL_USER: 'SAVE_EMAIL_USER',
  SAVE_INFO_USER: 'SAVE_INFO_USER',
  CLEAR_USER_STATE: 'CLEAR_USER_STATE',
};
